source 'https://rubygems.org'

gem 'rails', '~>2.3'
gem 'rspec', '~>1.3'
gem 'rspec-rails', '~>1.3'
gem 'mysql2', '<0.3'
gem 'ruby-debug', :platforms => :mri_18
gem 'test-unit', '~>1.2', :platforms => :ruby_19
gem 'hoe', '=2.8.0', :platforms => :ruby_19
gem 'rdoc', :require => false

gem 'secret_service', :path => '../..'
