source 'https://rubygems.org'

gem 'rails', '~>3.0.17'
gem 'rspec'
gem 'rspec-rails'
gem 'shoulda-matchers'
gem 'mysql2', '<0.3'
gem 'ruby-debug', :platforms => :mri_18
gem 'database_cleaner'

gem 'secret_service', :path => '../..'
